/*
 * DOCSMOREAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const config = require("../../lib/configuration");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.AVAILABLEENDPOINTSController;
const GetOAuthTOKENRequest = testerlib.GetOAuthTOKENRequest;


describe("AVAILABLEENDPOINTSController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * In Docsmore space, Flow Track means all the client documents generated using one of the Document Flow. In other words, it is an instance of Document FLow. The other thing to notice here is payload information is remarkably similar to general "Workflow" of a Single Document.

When you initiate this API call, you are basically setting up a new instance of Workflow and in turn getting workflow link of the starting document in the workflow.
     */
    it("should testGetWorkflowLinkForFlowTrack response", function testGetWorkflowLinkForFlowTrackTest(done) {
        // parameters for the API call
        let accept = 'application/json';
        let contentType = 'application/json';

        controller.createGetWorkflowLinkForFlowTrack(accept, contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * Todo Add description for test testGetAllDocumentFlows
     */
    it("should testGetAllDocumentFlows response", function testGetAllDocumentFlowsTest(done) {
        // parameters for the API call
        let accept = 'application/json';
        let contentType = 'application/json';

        controller.getAllDocumentFlows(accept, contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * This is the most popular use of Docsmore API. From your connected app, you can launch workflow and obtain the unique link for immediate launch or later on. You can also supply data in flat json format that can be used inside the document for pre-fill purpose saving your customer time.

Please make sure you pay close attention to the requirement for this API call as there are several aspects of it as required parameters.
     */
    it("should testGetWorkflowLink response", function testGetWorkflowLinkTest(done) {
        // parameters for the API call
        let accept = 'application/json';
        let contentType = 'application/json';

        controller.createGetWorkflowLink(accept, contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * By design, the authenticated user can only view the files that are either created by them or shared with them. Make sure user has at least read permission to view the catalogue.
     */
    it("should testFetchAllDocumentsFromYourTeamCatalogue response", function testFetchAllDocumentsFromYourTeamCatalogueTest(done) {
        // parameters for the API call
        let items = '{{items}}';
        let page = '{{page}}';
        let accept = 'application/json';
        let contentType = 'application/json';

        controller.fetchAllDocumentsFromYourTeamCatalogue(items, page, accept, contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
