/*
 * DOCSMOREAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.OAUTHTOKENController;
const GetOAuthTOKENRequest = testerlib.GetOAuthTOKENRequest;

describe("OAUTHTOKENController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * 
Obtaining an Auth Token is the first thing in the process. The lifetime of Auth token is configurable in the developer portal depending upon your need. Once auth token is obtained, all the follow up API calls will need to include auth token in the header. FaIlure to do so would result in response with 401 Unauthorized Access.

Under Your Developer Account - Go to Api Setting and you will screen similar to below.
<img src="https://www.docsmore.com/wp-content/uploads/2018/02/apikey-screen.png" alt="alt text" title="Title" />

Make sure you call this in server side code. Exposing apiKey and clientSecret is a not a good idea on front end and can lead up to security vulnerabilities.
     */
    it("should testGetOAuthTOKEN response", function testGetOAuthTOKENTest(done) {
        // parameters for the API call
        let body = baseController.getObjectMapper().mapObject({
	"client_id": "[API KEY]",
	"client_secret": "[CLIENT SECRET]"
}, 'GetOAuthTOKENRequest');
        let accept = 'application/json';
        let contentType = 'application/json';

        controller.createGetOAuthTOKEN(body, accept, contentType, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
